{{- if .Values.persistentVolumeClaim.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  annotations:
      volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes: {{ toYaml .Values.persistentVolumeClaim.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.requests.storage }}
  selector:
    matchLabels:
      usage: camera-trap-fileshare-pv
{{- end }}